optimizer: AdamW
lr: 0.001
weight_decay: 0.05
batch_size: 128
epochs: 100
amp: true
scheduler:
  name: cosine
  warmup_epochs: 5
early_stop:
  monitor: val_loss
  patience: 10
threshold_policy: youden
# training seeds (experiment runs iterate over this trio; dataset packs use their own seeds)
seeds: [13, 29, 47]
image_size: 224
num_workers: 8
prefetch_factor: 2
pin_memory: true
persistent_workers: true
log_interval: 10
